version: '3'
services:
  nginx:
    image: nginx:1.17.6
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ".:/src"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-fpm
    networks:
      - supermetrics_network

  php-fpm:
    image: php:7.4.0-fpm
    volumes:
      - ".:/src"
    networks:
      - supermetrics_network

networks:
  supermetrics_network:
    driver: bridge
